FROM centos:CENTOS_VERSION

ARG BUILD_DATE
ARG VCS_REF
ARG VERSION=CENTOS_VERSION

LABEL \
    org.label-schema.name="jumanjiman/infiniband" \
    org.label-schema.description="Infiniband base image based on Centos" \
    org.label-schema.url="https://github.com/jumanjihouse/docker-infiniband" \
    org.label-schema.vcs-url="https://github.com/jumanjihouse/docker-infiniband.git" \
    org.label-schema.docker.dockerfile="/Dockerfile.in" \
    org.label-schema.vcs-type="Git" \
    org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.version=$VERSION

RUN yum -y install CENTOS_RPMS && \
    yum -y update && \
    yum clean all

# http://www.mellanox.com/page/mlxup_firmware_tool
#
# mlxup - a Mellanox firmware update and query utility.
# The utility enables scanning the server machine for
# available Mellanox adapters and indicates
# whether firmware update is required for each adapter.
# To make it easier for customers the mlxup can also
# automatically update the latest firmware either from the web,
# or use binaries provided locally.
#
ADD http://www.mellanox.com/downloads/firmware/mlxup/4.9.0/SFX/linux_x64/mlxup /usr/sbin/mlxup
RUN chmod 0755 /usr/sbin/mlxup

# GNU compiler
RUN yum install -y \
        gcc \
        gcc-c++ \
        gcc-gfortran && \
    rm -rf /var/cache/yum/*

# OpenMPI version 3.3.1
RUN yum install -y \
        bzip2 \
        file \
        hwloc \
        make \
        numactl-devel \
        openssh-clients \
        perl \
        tar \
        wget && \
    rm -rf /var/cache/yum/*
RUN mkdir -p /var/tmp && wget -q -nc --no-check-certificate -P /var/tmp https://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.7.tar.bz2 && \
    mkdir -p /var/tmp && tar -x -f /var/tmp/openmpi-1.10.7.tar.bz2 -C /var/tmp -j && \
    cd /var/tmp/openmpi-1.10.7 && CC=gcc CXX=g++ F77=gfortran FC=gfortran ./configure --prefix=/usr/local/openmpi --disable-getpwuid --enable-orterun-prefix-by-default && \
    make -j$(nproc) && \
    make -j$(nproc) install && \
    rm -rf /var/tmp/openmpi-1.10.7.tar.bz2 /var/tmp/openmpi-1.10.7
ENV LD_LIBRARY_PATH=/usr/local/openmpi/lib:$LD_LIBRARY_PATH \
    PATH=/usr/local/openmpi/bin:$PATH
